services:
  - type: web
    name: tq-erp-demo
    env: python
    plan: free

    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER
        value: "admin"
      - key: ADMIN_PASSWORD
        value: "123456"
      - key: COMPANY_NAME
        value: "常州市彤奇机械有限公司"
